spring:
  cloud:
    function:
      definition: processTemperature
    stream:
      bindings:
        processTemperature-in-0:
          destination: iot-temp
          group: reactive-processor-group
        processTemperature-out-0:
          destination: dashboard-data  # Hierheen stuurt hij de DashboardMetric
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}