apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactive-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive-processor
  template:
    metadata:
      labels:
        app: reactive-processor
    spec:
      containers:
        - name: reactive-processor
          image: vandenende/reactive-processor:latest
          imagePullPolicy: Never # Hij kijkt naar je lokale Docker images
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "redpanda:29092" # Let op: dit moet de K8s-naam zijn!